name: flutter_application_1
description: Descripción de tu app.

version: 0.1.0
environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/img1.jpg
    - assets/img/img2.jpg
    - assets/img/img3.jpg
    - assets/img/img4.jpg
    - assets/img/place1.jpg
    - assets/img/place2.jpg
    - assets/img/place3.jpg
    - assets/img/place4.jpg